create table if not exists public.enquiries (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    phone text not null,
    company text default '',
    service text not null,
    message text not null,
    source_page text default '',
    created_at timestamptz not null default now()
);

create table if not exists public.career_applications (
    id bigint generated by default as identity primary key,
    application_type text not null,
    full_name text not null,
    email text not null,
    phone text not null,
    location text default '',
    position text not null,
    college text default '',
    degree text default '',
    branch text default '',
    semester text default '',
    internship_skills text default '',
    experience text default '',
    current_company text default '',
    expected_ctc text default '',
    notice_period text default '',
    job_skills text default '',
    resume_filename text not null,
    resume_path text not null,
    linkedin text default '',
    github text default '',
    portfolio text default '',
    message text default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_enquiries_created_at on public.enquiries(created_at desc);
create index if not exists idx_career_applications_created_at on public.career_applications(created_at desc);
create index if not exists idx_career_applications_email on public.career_applications(email);

-- In Supabase Storage, create a PRIVATE bucket named: resumes
-- Do not put the service-role key in frontend code.
